#!/usr/bin/env python3
"""Fix all templated descriptions and related links in tools.json"""
import json

with open("tools.json", encoding="utf-8-sig") as f:
    data = json.load(f)

# Unique, useful descriptions per tool
descs = {
    # === Developer Tools ===
    "json-formatter": "Paste minified or messy JSON and get clean, indented output instantly. Validates syntax and highlights errors so you can fix them fast.",
    "json-validator": "Check if your JSON is valid before deploying. Shows the exact error location with line numbers so you can fix syntax mistakes quickly.",
    "json-minifier": "Strip whitespace and comments from JSON to reduce file size. Perfect for compressing API responses and config files before deployment.",
    "json-to-csv": "Turn nested or flat JSON arrays into CSV spreadsheets. Automatically maps keys to columns so you can open the data in Excel or Google Sheets.",
    "csv-to-json": "Convert CSV rows into clean JSON objects. Paste your spreadsheet data or delimited text and get structured JSON for APIs and databases.",
    "xml-formatter": "Pretty-print minified XML with proper indentation and line breaks. Makes messy SOAP or config files readable at a glance.",
    "xml-validator": "Check XML for syntax errors and malformed tags. Validates your document structure and shows exactly where corrections are needed.",
    "yaml-formatter": "Clean up messy YAML with consistent indentation. Works with nested objects, arrays, and multi-line strings for readable config files.",
    "yaml-to-json": "Convert YAML configuration files to JSON format. Useful when you need to feed YAML data into APIs or tools that only accept JSON.",
    "json-to-yaml": "Transform JSON data into clean YAML format. Ideal for converting API responses into human-readable Kubernetes or Docker configs.",
    "base64-encoder": "Encode any text or binary data to Base64. Useful for embedding images in HTML/CSS, encoding credentials for HTTP Basic Auth, or transferring binary data as text.",
    "base64-decoder": "Decode Base64-encoded strings back to readable text or raw data. Paste an encoded string to reveal the original content instantly.",
    "url-encoder": "Convert special characters in URLs to percent-encoded format (%20 for spaces, %26 for &). Essential for building query strings and API requests.",
    "url-decoder": "Decode percent-encoded URL strings back to readable text. Paste a messy URL with %20 and other codes to see the original characters.",
    "html-entity-encoder": "Convert special characters (<, >, &, quotes) to HTML entity codes. Safely display user input or code snippets in HTML without breaking your page layout.",
    "html-entity-decoder": "Convert HTML entity codes (&lt;, &amp;, &#39;) back to readable characters. Decode escaped text from HTML source or email templates.",
    "uuid-generator": "Generate v4 UUIDs (random unique identifiers) for database primary keys, API tokens, session IDs, or any system that needs globally unique IDs.",
    "random-string-generator": "Create random strings of any length with customizable character sets. Use for API keys, temporary passwords, tokens, or testing data.",
    "hash-generator": "Compute SHA-256, SHA-1, SHA-384, or SHA-512 hashes from any input text. Useful for checksums, password hashing verification, and data integrity checks.",
    "jwt-decoder": "Decode JWT (JSON Web Token) strings to view the header, payload, and signature. Debug authentication tokens without installing any tools.",
    "unix-timestamp-converter": "Convert Unix timestamps to human-readable dates and back. Debug API timestamps, log files, and database records with instant conversion.",
    "cron-expression-generator": "Build cron expressions with a visual picker. Generate the correct syntax for scheduled tasks in Linux, GitHub Actions, or CI/CD pipelines.",
    "regex-tester": "Test regular expressions against sample text in real-time. See match positions and groups to debug patterns before using them in your code.",
    "regex-generator": "Describe what you want to match in plain English and get a working regular expression. No need to memorize regex syntax for common patterns.",
    "lorem-ipsum-generator": "Generate placeholder text for mockups, wireframes, and design prototypes. Choose paragraphs, sentences, or words in the quantity you need.",

    # === CSS/HTML Tools ===
    "css-minifier": "Remove comments, whitespace, and line breaks from CSS to reduce file size. Faster page loads by shrinking your stylesheets.",
    "css-beautifier": "Format compressed CSS with proper indentation and line breaks. Make minified stylesheets readable for debugging and editing.",
    "html-minifier": "Strip comments, whitespace, and redundant tags from HTML to reduce page size. Faster loads without changing visible content.",
    "html-beautifier": "Add proper indentation and line breaks to minified or messy HTML. Read and edit generated or compressed markup easily.",
    "javascript-minifier": "Remove whitespace, comments, and shorten variable names in JavaScript to produce smaller, faster-loading script files.",
    "javascript-beautifier": "Format minified JavaScript with proper indentation and line breaks. Debug and understand compressed scripts without hunting through single-line code.",
    "css-gradient-generator": "Create linear, radial, and conic gradients visually. Pick colors, angles, and stops with a live preview, then copy the CSS code.",
    "css-box-shadow-generator": "Design box shadows with controls for offset, blur, spread, and color. See the effect in real time and copy the CSS for your elements.",
    "css-border-radius-generator": "Set per-corner border radius values visually. Create rounded corners, pill shapes, or asymmetric designs with live preview.",
    "css-text-shadow-generator": "Add text shadows with blur, offset, and color controls. See how different shadow styles look on your text before copying the CSS.",
    "css-button-generator": "Design styled buttons with padding, colors, borders, and hover effects. Generate the complete CSS for buttons you can paste into your project.",
    "css-glassmorphism-generator": "Create frosted-glass effects with background blur, transparency, and border controls. Generate modern glassmorphism CSS for cards and overlays.",
    "css-neumorphism-generator": "Build soft 3D shadow effects for buttons and cards. Adjust light and shadow direction to create the neumorphic look.",
    "css-transform-generator": "Combine translate, rotate, scale, and skew transforms visually. See the result on a preview element and copy the combined CSS.",
    "css-animation-generator": "Create keyframe animations for fading, sliding, scaling, and bouncing. Set duration and easing, then copy the CSS animation code.",
    "css-flexbox-generator": "Design flexbox layouts by picking direction, alignment, wrapping, and gaps. Visualize the result and copy the CSS for your container.",
    "css-grid-generator": "Build CSS Grid layouts by defining rows, columns, and gaps. Preview the grid structure and copy the complete CSS.",
    "css-clamp-generator": "Generate fluid typography and spacing with CSS clamp(). Set min, preferred, and max values for responsive sizing without media queries.",
    "css-filter-generator": "Apply blur, brightness, contrast, grayscale, and other CSS filters visually. Adjust sliders and copy the filter code.",
    "css-color-converter": "Convert between HEX, RGB, HSL, and HWB color formats instantly. Pick a color and get all format variants for your CSS.",

    # === Text Tools ===
    "word-counter": "Count words, characters, sentences, and estimate reading time instantly. Perfect for checking essay limits, blog post length, and copywriting targets.",
    "character-counter": "Count characters with and without spaces. Check text length for social media posts, meta descriptions, and form input limits.",
    "sentence-counter": "Count the number of sentences in your text. Useful for readability analysis and checking writing density.",
    "paragraph-counter": "Count paragraphs in your document. Quick check for assignment requirements or content structure.",
    "reading-time-calculator": "Estimate how long it takes to read your text at average speed. Great for blog posts, articles, and documentation.",
    "case-converter": "Convert text between uppercase, lowercase, title case, and sentence case. Fix capitalization mistakes or format text for different contexts.",
    "uppercase-converter": "Convert all text to uppercase instantly. Useful for headings, emphasis, or formatting requirements.",
    "lowercase-converter": "Convert all text to lowercase. Fix accidental caps lock or normalize text for comparison and processing.",
    "title-case-converter": "Capitalize the first letter of each word automatically. Format titles, headings, and proper nouns consistently.",
    "remove-duplicate-lines": "Delete repeated lines from text while keeping the first occurrence. Clean up log files, lists, or any text with unwanted duplicates.",
    "sort-lines-alphabetically": "Sort text lines in ascending or descending alphabetical order. Organize lists, data, and log entries quickly.",
    "reverse-text": "Reverse text character by character or word by word. Useful for debugging, puzzles, or mirror-text effects.",
    "remove-extra-spaces": "Collapse multiple spaces and tabs into single spaces. Clean up messy text copied from PDFs or formatted documents.",
    "find-and-replace-tool": "Search for specific text and replace it with new text across your entire document. Works like a word processor find-and-replace.",
    "text-diff-checker": "Compare two text inputs side-by-side and highlight the differences. Spot changes between document versions or code revisions.",
    "text-cleaner": "Remove line breaks, extra whitespace, and non-printable characters. Clean messy text copied from emails, PDFs, or web pages.",
    "text-to-slug-converter": "Convert any text to a URL-friendly slug. Translates spaces to hyphens, removes special characters, and lowercases everything.",
    "slug-generator": "Generate URL slugs from page titles or headings. SEO-friendly format with lowercase, hyphens, and no special characters.",
    "markdown-previewer": "Write Markdown on the left and see the rendered HTML on the right. Live preview for README files, documentation, and blog posts.",
    "markdown-table-generator": "Create Markdown tables by defining rows and columns visually. Copy the formatted table syntax for GitHub, docs, or wikis.",
    "markdown-to-html-converter": "Convert Markdown syntax to clean HTML. Paste your Markdown and get copy-ready HTML for emails, websites, or CMS content.",
    "html-to-markdown-converter": "Convert HTML pages or snippets to clean Markdown. Extract content from websites for documentation or static site generators.",
    "text-to-ascii-generator": "Convert text to ASCII character codes (decimal, octal, hex). Useful for encoding, debugging character issues, or learning ASCII values.",
    "ascii-art-generator": "Convert text into ASCII art using different font styles. Create decorative text for terminals, code comments, or social media.",
    "text-line-break-remover": "Remove hard line breaks from text while preserving paragraph structure. Clean up copy-pasted content from PDFs and emails.",

    # === Math Calculators ===
    "percentage-calculator": "Find X% of any number, or calculate what percentage one number is of another. Instant results with the formula shown.",
    "percentage-increase-calculator": "Calculate percentage increase between two numbers. Enter the original and new values to see the exact percentage change.",
    "percentage-decrease-calculator": "Calculate percentage decrease between two numbers. Enter the original and new values to see the exact drop.",
    "ratio-calculator": "Find the ratio between two numbers in simplest form. Enter two values to get the ratio as A:B and as a fraction.",
    "proportion-calculator": "Solve proportion problems (A/B = C/D). Enter three known values to find the missing one.",
    "average-calculator": "Calculate the arithmetic mean of any set of numbers. Enter values separated by commas to get the average instantly.",
    "median-calculator": "Find the middle value of a sorted number set. Useful for finding the median when data has outliers.",
    "mode-calculator": "Find the most frequently occurring number in a data set. Works with single and multi-modal data.",
    "standard-deviation-calculator": "Calculate population or sample standard deviation. Shows the formula and step-by-step result.",
    "mean-calculator": "Calculate the arithmetic mean (average) of numbers. Enter values to get the sum divided by count.",
    "fraction-calculator": "Add, subtract, multiply, or divide fractions. Shows the result in lowest terms with the working steps.",
    "decimal-to-fraction": "Convert any decimal number to its fraction equivalent. Shows the fraction in simplified form.",
    "fraction-to-decimal": "Convert any fraction to its decimal equivalent. Shows the result rounded to the precision you need.",
    "mixed-number-calculator": "Convert between mixed numbers and improper fractions, or calculate with mixed numbers directly.",
    "gcd-calculator": "Find the Greatest Common Divisor of two or more numbers. Useful for simplifying fractions and finding common factors.",
    "lcm-calculator": "Find the Least Common Multiple of two numbers. Essential for adding fractions with different denominators.",
    "prime-number-checker": "Check if a number is prime or composite. Enter any positive integer to get an instant answer.",
    "prime-number-generator": "Generate a list of prime numbers up to a given limit. Useful for cryptography, math problems, and testing.",
    "factor-calculator": "Find all factors (divisors) of a number. Enter any positive integer to see every number that divides it evenly.",
    "scientific-notation-converter": "Convert between standard notation and scientific notation (e.g. 123000 = 1.23 × 10^5).",
    "binary-calculator": "Perform arithmetic on binary numbers. Add, subtract, multiply, or divide in base-2.",
    "binary-to-decimal": "Convert binary (base-2) numbers to decimal (base-10). Enter a binary string to get the decimal equivalent.",
    "decimal-to-binary": "Convert decimal numbers to binary (base-2). Enter any number to see its binary representation.",
    "hex-to-decimal": "Convert hexadecimal (base-16) to decimal (base-10). Enter a hex value to get the decimal number.",
    "decimal-to-hex": "Convert decimal numbers to hexadecimal (base-16). Enter any number to see its hex representation.",
    "octal-converter": "Convert between octal (base-8) and decimal (base-10) number systems. Enter a value in either format.",
    "roman-numeral-converter": "Convert between Roman numerals and Arabic numbers. Enter 1–3999 to get the Roman numeral, or vice versa.",
    "random-number-generator": "Generate random integers or decimals within any range. Set minimum, maximum, and quantity for custom random numbers.",
    "exponent-calculator": "Calculate any base raised to any power. Enter the base and exponent to get the result instantly.",
    "square-root-calculator": "Calculate the square root of any positive number. Shows the result with decimal precision.",

    # === Student Tools ===
    "grade-calculator": "Convert test scores to letter grades (A–F). Enter marks obtained and total to see your percentage and grade.",
    "gpa-calculator": "Calculate your GPA by entering course grades and credit hours. Supports the standard 4.0 scale.",
    "cgpa-calculator": "Calculate your Cumulative GPA across multiple semesters. Add courses from each term to get your overall CGPA.",
    "percentage-to-gpa-calculator": "Convert a percentage score to GPA on the 4.0 scale. Enter your percentage to see the equivalent GPA.",
    "exam-percentage-calculator": "Calculate your exam percentage from marks obtained and total marks. Quick result with the formula shown.",
    "marks-percentage-calculator": "Find the percentage of marks you scored. Enter marks obtained and maximum marks for an instant calculation.",
    "final-grade-calculator": "Calculate what grade you need on the final exam to achieve your target course grade. Enter current grade and weight.",
    "weighted-grade-calculator": "Calculate your grade with different weights for assignments, exams, and participation. Enter each component and its percentage weight.",
    "study-time-calculator": "Estimate how many hours you need to study based on topic difficulty and exam date. Plan your revision schedule.",
    "pomodoro-timer": "Work in focused 25-minute intervals with 5-minute breaks. Track completed Pomodoro sessions for productive study time.",
    "exam-countdown": "Count down the days, hours, and minutes until your exam. Set the date and see exactly how much time you have left.",
    "assignment-countdown": "Track how many days remain until your assignment is due. Set the deadline and stay on top of your submissions.",
    "semester-countdown": "See how many days are left in the current semester. Set the end date to track remaining study time.",
    "study-schedule-generator": "Create a weekly study timetable based on your subjects and available hours. Print or copy the generated schedule.",
    "revision-schedule-generator": "Plan your revision sessions leading up to exams. Allocates topics across available days for balanced preparation.",
    "flashcard-generator": "Create study flashcards with a question on one side and answer on the other. Export for Anki or print for offline study.",
    "random-quiz-generator": "Generate a random quiz from your own question bank. Set the number of questions and get a unique quiz each time.",
    "multiplication-table-generator": "Generate multiplication tables for any number. See the table formatted for quick reference or printing.",
    "times-table-quiz": "Practice multiplication tables with timed quizzes. Test your speed and accuracy on times tables from 1 to 20.",
    "random-math-quiz": "Generate random math problems at different difficulty levels. Practice addition, subtraction, multiplication, and division.",
    "equation-solver": "Solve linear equations step by step. Enter your equation and see the solution with the working shown.",
    "quadratic-equation-solver": "Solve quadratic equations using the quadratic formula. Enter coefficients a, b, and c to get real and complex roots.",
    "factorial-calculator": "Calculate n! (n factorial) for any non-negative integer. See the step-by-step multiplication.",
    "scientific-calculator": "Perform advanced math: trigonometry, logarithms, powers, roots, and more. A full scientific calculator in your browser.",
    "unit-conversion-calculator": "Convert between units of length, weight, temperature, volume, and more. Supports dozens of common unit pairs.",

    # === Date & Time ===
    "age-calculator": "Find your exact age in years, months, and days. Enter any birth date to see how old someone is today.",
    "date-difference-calculator": "Calculate the exact number of days between any two dates. Useful for project timelines, age gaps, and deadlines.",
    "days-between-dates": "Find how many days are between two dates. Enter start and end dates for an instant count.",
    "weeks-between-dates": "Calculate the number of weeks between two dates. Enter any two dates to get the week difference.",
    "months-between-dates": "Find how many months are between two dates. Useful for contract durations, subscription periods, and age calculations.",
    "business-days-calculator": "Count only working days (Monday–Friday) between two dates. Excludes weekends for accurate project planning.",
    "working-days-calculator": "Calculate working days between two dates. Similar to business days, useful for shift planning and deadlines.",
    "days-until-date": "Count down from today to any future date. See exactly how many days remain until your event or deadline.",
    "date-addition-calculator": "Add days, weeks, months, or years to any date. Find out what date it will be after a given period.",
    "date-subtraction-calculator": "Subtract days, weeks, months, or years from any date. Find out what date it was before a given period.",
    "time-difference-calculator": "Calculate the difference between two times. See hours, minutes, and seconds between any two timestamps.",
    "time-duration-calculator": "Calculate total duration from start and end times. Convert hours and minutes to total minutes or hours.",
    "hours-to-minutes-converter": "Convert hours to minutes instantly. Enter any number of hours to get the equivalent in minutes.",
    "minutes-to-seconds-converter": "Convert minutes to seconds. Enter any number to see the conversion.",
    "seconds-to-hours-converter": "Convert seconds to hours and minutes. Enter a total seconds value to get the human-readable duration.",
    "unix-timestamp-generator": "Get the current Unix timestamp (seconds since Jan 1, 1970) or convert a date to Unix time.",
    "leap-year-checker": "Check if a year is a leap year. Enter any year to find out if it has 366 days.",
    "day-of-week-calculator": "Find out what day of the week any date falls on. Enter a date to see Monday, Tuesday, etc.",
    "week-number-calculator": "Find the ISO week number for any date. Enter a date to see which week of the year it is.",
    "date-format-converter": "Convert dates between formats: ISO 8601, US (MM/DD/YYYY), UK (DD/MM/YYYY), and more.",

    # === Finance Calculators ===
    "simple-interest-calculator": "Calculate simple interest using I = P × R × T. Enter principal, rate, and time to see the interest earned or owed.",
    "compound-interest-calculator": "Calculate compound interest with monthly, quarterly, or annual compounding. See total amount and interest earned.",
    "loan-emi-calculator": "Calculate your Equated Monthly Installment for any loan. Enter principal, interest rate, and tenure to see your EMI.",
    "mortgage-calculator": "Estimate monthly mortgage payments for home loans. Enter loan amount, rate, and term to see principal and interest split.",
    "loan-payment-calculator": "Calculate total loan payments including interest. See monthly payment amount and total cost of borrowing.",
    "loan-interest-calculator": "Find the total interest you'll pay on a loan. Compare different interest rates to find the cheapest option.",
    "investment-return-calculator": "Calculate returns on your investment. Enter initial amount, rate, and duration to see projected value.",
    "cagr-calculator": "Calculate the Compound Annual Growth Rate of an investment. Enter beginning value, ending value, and years.",
    "sip-calculator": "Estimate returns on Systematic Investment Plans (SIP). Enter monthly amount, rate, and duration for projected value.",
    "inflation-calculator": "See how inflation erodes purchasing power over time. Enter current amount and inflation rate to find future value.",
    "savings-goal-calculator": "Find how much you need to save monthly to reach a financial goal. Enter target amount, timeline, and interest rate.",
    "retirement-calculator": "Estimate how much you need to save for retirement. Enter current savings, monthly contribution, and expected returns.",
    "discount-calculator": "Calculate the discounted price and savings. Enter original price and discount percentage to see the final price.",
    "sale-price-calculator": "Find the sale price after a discount. Enter the original price and discount amount or percentage.",
    "markup-calculator": "Calculate the selling price from cost and markup percentage. Enter cost and margin to set your price.",
    "profit-margin-calculator": "Calculate net profit margin from revenue and costs. See your margin as a percentage.",
    "break-even-calculator": "Find how many units you need to sell to break even. Enter fixed costs, variable cost per unit, and selling price.",
    "tip-calculator": "Calculate the tip and total bill. Enter the bill amount and tip percentage (10%, 15%, 20%) to see the split.",
    "split-bill-calculator": "Split a bill evenly between any number of people. Enter total and headcount to see per-person amount.",
    "salary-calculator": "Convert between annual, monthly, weekly, and hourly salary. See take-home pay after taxes.",
    "hourly-to-yearly-salary": "Convert your hourly wage to annual salary. Enter hourly rate and hours per week for the yearly equivalent.",
    "yearly-to-hourly-salary": "Convert annual salary to hourly rate. Enter yearly salary and weekly hours for the per-hour amount.",
    "tax-percentage-calculator": "Calculate what percentage of your income goes to taxes. Enter gross and net income to see the effective tax rate.",
    "budget-calculator": "Plan your monthly budget by allocating income to categories. See where your money goes with a clear breakdown.",
    "net-worth-calculator": "Calculate your total net worth. Add up assets and subtract liabilities to see your financial position.",

    # === Business Calculators ===
    "profit-calculator": "Calculate profit from revenue and costs. See gross and net profit with the formula breakdown.",
    "revenue-calculator": "Calculate total revenue from units sold and price per unit. Quick sales and pricing calculations.",
    "roi-calculator": "Calculate Return on Investment (ROI). Enter cost and return to see the percentage gain or loss.",
    "roas-calculator": "Calculate Return on Ad Spend. Enter ad spend and revenue to see if your campaigns are profitable.",
    "conversion-rate-calculator": "Find your conversion rate from visitors and conversions. Essential metric for marketing and e-commerce.",
    "ctr-calculator": "Calculate Click-Through Rate from impressions and clicks. Measure the effectiveness of ads and links.",
    "cpm-calculator": "Calculate Cost Per Mille (per 1000 impressions). Compare ad pricing across different campaigns.",
    "cpc-calculator": "Calculate Cost Per Click from total spend and total clicks. Evaluate your paid advertising efficiency.",
    "customer-acquisition-cost-calculator": "Find how much it costs to acquire one customer. Enter total marketing spend and new customers gained.",
    "customer-lifetime-value-calculator": "Calculate the total revenue a customer generates over their lifetime. Compare against acquisition cost.",
    "churn-rate-calculator": "Calculate customer churn rate. Enter starting and ending customers to see the percentage lost.",
    "growth-rate-calculator": "Calculate growth rate between two periods. Enter old and new values to see the percentage change.",
    "gross-margin-calculator": "Calculate gross margin from revenue and cost of goods sold. See the percentage of revenue retained.",
    "net-margin-calculator": "Calculate net profit margin after all expenses. See what percentage of revenue becomes profit.",
    "markup-vs-margin-calculator": "Compare markup and margin side by side. Understand the difference and convert between them.",
    "inventory-turnover-calculator": "Calculate how quickly inventory sells. Enter COGS and average inventory to see turnover ratio.",
    "sales-commission-calculator": "Calculate sales commission from revenue and commission rate. Quick payout calculation for sales teams.",
    "break-even-units-calculator": "Find how many units you need to sell to cover all costs. Enter fixed costs, price, and variable cost per unit.",
    "saas-pricing-calculator": "Calculate SaaS pricing based on costs, margins, and target revenue. Find the right price for your product.",
    "freelance-hourly-rate-calculator": "Calculate your ideal hourly rate based on expenses, desired income, and billable hours.",

    # === Image Tools ===
    "image-resizer": "Resize images to exact dimensions in pixels. Maintain aspect ratio or force specific width and height. All processing in your browser.",
    "image-cropper": "Crop images to remove unwanted areas. Set custom dimensions or drag to select the crop area. No uploads needed.",
    "image-compressor": "Reduce image file size without visible quality loss. Supports JPEG, PNG, and WebP. Perfect for faster web pages.",
    "jpg-to-png": "Convert JPG images to PNG format for lossless quality and transparency support. All conversion happens in your browser.",
    "png-to-jpg": "Convert PNG images to smaller JPG files. Reduce file size when transparency isn't needed.",
    "webp-to-jpg": "Convert WebP images to JPG for wider compatibility with older software and browsers.",
    "jpg-to-webp": "Convert JPG images to modern WebP format for smaller file sizes with similar quality.",
    "png-to-webp": "Convert PNG images to WebP for significantly smaller file sizes while maintaining quality.",
    "gif-frame-extractor": "Extract individual frames from animated GIFs. View and save each frame as a separate image.",
    "image-metadata-viewer": "View EXIF metadata in images: camera model, GPS coordinates, date taken, shutter speed, and more.",
    "image-dimension-checker": "Check exact pixel dimensions of an image. Useful for verifying sizes before uploading to websites or social media.",
    "image-aspect-ratio-calculator": "Calculate and compare aspect ratios. Enter width and height to see the ratio (16:9, 4:3, etc.).",
    "favicon-generator": "Generate favicon files from any image. Creates standard favicon.ico and PNG sizes for your website.",
    "app-icon-generator": "Generate app icons in all required sizes from a single image. iOS, Android, and PWA icon sets.",
    "social-media-image-resizer": "Resize images for Facebook, Twitter, Instagram, LinkedIn, and Pinterest. Get exact dimensions for each platform.",
    "youtube-thumbnail-resizer": "Resize images to YouTube thumbnail dimensions (1280×720). Ensure your thumbnail displays correctly.",
    "instagram-image-resizer": "Resize images for Instagram posts (1080×1080) and stories (1080×1920). Crop and preview before posting.",
    "image-pixel-color-picker": "Pick any color from an image by clicking on it. Get the exact HEX, RGB, and HSL values.",
    "image-to-base64": "Convert images to Base64-encoded strings. Embed images directly in HTML, CSS, or JSON without separate files.",
    "base64-to-image": "Decode Base64 strings back into viewable images. Paste the encoded data to see the original image.",

    # === Color Tools ===
    "hex-to-rgb": "Convert HEX color codes (#2563eb) to RGB values (37, 99, 235). Instant conversion for CSS and design tools.",
    "rgb-to-hex": "Convert RGB color values to HEX format. Enter red, green, and blue values to get the #hex code.",
    "rgb-to-hsl": "Convert RGB colors to HSL (Hue, Saturation, Lightness). Useful for creating color variations and themes.",
    "hsl-to-rgb": "Convert HSL color values back to RGB. Enter hue, saturation, and lightness for the standard color values.",
    "hex-to-hsl": "Convert HEX colors directly to HSL format. Skip the RGB step for faster color workflow.",
    "color-picker": "Pick any color visually or enter a HEX/RGB value. See the color preview with all format conversions.",
    "color-palette-generator": "Generate a harmonious color palette from a base color. Choose from complementary, analogous, or triadic schemes.",
    "random-color-generator": "Generate random colors with one click. Get the HEX, RGB, and HSL values for each color.",
    "gradient-generator": "Create multi-stop gradients with custom colors and angles. Preview the gradient and copy the CSS code.",
    "complementary-color-generator": "Find the complementary color (opposite on the color wheel) for any base color. Great for contrasting designs.",
    "analogous-color-generator": "Generate analogous colors (neighbors on the color wheel). Create smooth, harmonious color schemes.",
    "triadic-color-generator": "Find three evenly-spaced colors on the color wheel. Bold, balanced color schemes for design projects.",
    "contrast-checker": "Check color contrast ratio between two colors. Ensures readability for text on backgrounds.",
    "wcag-contrast-checker": "Test color combinations against WCAG 2.1 accessibility standards. Get AA and AAA pass/fail results.",
    "color-blindness-simulator": "Preview how your colors look to people with different types of color blindness. Test deuteranopia, protanopia, and more.",
    "css-color-generator": "Generate CSS color values in HEX, RGB, HSL, and named formats. Pick a color and get all formats.",
    "tailwind-color-converter": "Convert any color to the nearest Tailwind CSS color class. Find the closest match for custom colors.",
    "material-color-converter": "Convert colors to Material Design color palette values. Find the closest Material color for your design.",
    "rgb-color-mixer": "Mix two or more RGB colors together. Set ratios to blend colors and see the resulting shade.",
    "color-name-finder": "Find the name of any color from its HEX or RGB value. Identify CSS named colors, Pantone equivalents, and more.",
}

# Fix related links for topical clustering
related_fixes = {
    # JSON cluster
    "json-formatter": ["json-validator", "json-minifier", "json-to-csv", "csv-to-json", "json-to-yaml", "yaml-to-json"],
    "json-validator": ["json-formatter", "json-minifier", "json-to-csv", "xml-validator", "yaml-formatter", "csv-to-json"],
    "json-minifier": ["json-formatter", "json-validator", "json-to-csv", "csv-to-json", "json-to-yaml", "yaml-to-json"],
    "json-to-csv": ["csv-to-json", "json-formatter", "json-to-yaml", "yaml-to-json", "json-minifier", "json-validator"],
    "csv-to-json": ["json-to-csv", "json-formatter", "json-to-yaml", "yaml-to-json", "json-minifier", "xml-formatter"],
    # XML/YAML cluster
    "xml-formatter": ["xml-validator", "json-formatter", "yaml-formatter", "json-minifier", "csv-to-json", "yaml-to-json"],
    "xml-validator": ["xml-formatter", "json-validator", "yaml-formatter", "json-formatter", "yaml-to-json", "csv-to-json"],
    "yaml-formatter": ["yaml-to-json", "json-to-yaml", "xml-formatter", "json-formatter", "json-validator", "csv-to-json"],
    "yaml-to-json": ["json-to-yaml", "yaml-formatter", "json-formatter", "csv-to-json", "xml-formatter", "json-to-csv"],
    "json-to-yaml": ["yaml-to-json", "yaml-formatter", "json-formatter", "csv-to-json", "xml-formatter", "json-to-csv"],
    # Encoding cluster
    "base64-encoder": ["base64-decoder", "url-encoder", "url-decoder", "html-entity-encoder", "html-entity-decoder", "image-to-base64"],
    "base64-decoder": ["base64-encoder", "url-decoder", "url-encoder", "html-entity-decoder", "html-entity-encoder", "base64-to-image"],
    "url-encoder": ["url-decoder", "base64-encoder", "base64-decoder", "html-entity-encoder", "html-entity-decoder", "text-to-slug-converter"],
    "url-decoder": ["url-encoder", "base64-decoder", "base64-encoder", "html-entity-decoder", "html-entity-encoder", "slug-generator"],
    "html-entity-encoder": ["html-entity-decoder", "url-encoder", "url-decoder", "base64-encoder", "base64-decoder", "html-minifier"],
    "html-entity-decoder": ["html-entity-encoder", "url-decoder", "url-encoder", "base64-decoder", "base64-encoder", "html-beautifier"],
    # Dev utility cluster
    "uuid-generator": ["random-string-generator", "hash-generator", "random-number-generator", "json-formatter", "timestamp-converter", "json-validator"],
    "random-string-generator": ["uuid-generator", "hash-generator", "random-number-generator", "lorem-ipsum-generator", "json-formatter", "cron-expression-generator"],
    "hash-generator": ["uuid-generator", "random-string-generator", "jwt-decoder", "base64-encoder", "json-formatter", "json-validator"],
    "jwt-decoder": ["hash-generator", "json-formatter", "base64-decoder", "url-decoder", "uuid-generator", "json-validator"],
    "unix-timestamp-converter": ["unix-timestamp-generator", "date-difference-calculator", "date-format-converter", "hash-generator", "uuid-generator", "json-formatter"],
    "cron-expression-generator": ["regex-tester", "regex-generator", "uuid-generator", "hash-generator", "random-string-generator", "lorem-ipsum-generator"],
    "regex-tester": ["regex-generator", "cron-expression-generator", "find-and-replace-tool", "text-diff-checker", "hash-generator", "url-encoder"],
    "regex-generator": ["regex-tester", "cron-expression-generator", "uuid-generator", "hash-generator", "random-string-generator", "text-to-slug-converter"],
    "lorem-ipsum-generator": ["random-string-generator", "uuid-generator", "slug-generator", "text-to-slug-converter", "markdown-previewer", "markdown-table-generator"],
    # CSS/HTML min/beautify cluster
    "css-minifier": ["css-beautifier", "html-minifier", "javascript-minifier", "html-beautifier", "javascript-beautifier", "css-color-converter"],
    "css-beautifier": ["css-minifier", "html-beautifier", "javascript-beautifier", "html-minifier", "javascript-minifier", "css-gradient-generator"],
    "html-minifier": ["html-beautifier", "css-minifier", "javascript-minifier", "css-beautifier", "javascript-beautifier", "html-entity-encoder"],
    "html-beautifier": ["html-minifier", "css-beautifier", "javascript-beautifier", "css-minifier", "javascript-minifier", "html-to-markdown-converter"],
    "javascript-minifier": ["javascript-beautifier", "css-minifier", "html-minifier", "css-beautifier", "html-beautifier", "json-minifier"],
    "javascript-beautifier": ["javascript-minifier", "css-beautifier", "html-beautifier", "css-minifier", "html-minifier", "json-formatter"],
    # CSS generator cluster
    "css-gradient-generator": ["css-box-shadow-generator", "css-color-converter", "css-filter-generator", "css-animation-generator", "color-palette-generator", "gradient-generator"],
    "css-box-shadow-generator": ["css-text-shadow-generator", "css-gradient-generator", "css-border-radius-generator", "css-glassmorphism-generator", "css-neumorphism-generator", "css-button-generator"],
    "css-border-radius-generator": ["css-box-shadow-generator", "css-text-shadow-generator", "css-button-generator", "css-glassmorphism-generator", "css-transform-generator", "css-animation-generator"],
    "css-text-shadow-generator": ["css-box-shadow-generator", "css-button-generator", "css-glassmorphism-generator", "css-gradient-generator", "css-color-converter", "css-filter-generator"],
    "css-button-generator": ["css-box-shadow-generator", "css-glassmorphism-generator", "css-neumorphism-generator", "css-transform-generator", "css-text-shadow-generator", "css-border-radius-generator"],
    "css-glassmorphism-generator": ["css-neumorphism-generator", "css-button-generator", "css-box-shadow-generator", "css-filter-generator", "css-gradient-generator", "css-transform-generator"],
    "css-neumorphism-generator": ["css-glassmorphism-generator", "css-button-generator", "css-box-shadow-generator", "css-transform-generator", "css-filter-generator", "css-gradient-generator"],
    "css-transform-generator": ["css-animation-generator", "css-flexbox-generator", "css-grid-generator", "css-button-generator", "css-glassmorphism-generator", "css-neumorphism-generator"],
    "css-animation-generator": ["css-transform-generator", "css-flexbox-generator", "css-grid-generator", "css-button-generator", "css-gradient-generator", "css-box-shadow-generator"],
    "css-flexbox-generator": ["css-grid-generator", "css-transform-generator", "css-animation-generator", "css-clamp-generator", "css-filter-generator", "css-color-converter"],
    "css-grid-generator": ["css-flexbox-generator", "css-clamp-generator", "css-transform-generator", "css-animation-generator", "css-filter-generator", "css-color-converter"],
    "css-clamp-generator": ["css-flexbox-generator", "css-grid-generator", "css-color-converter", "css-filter-generator", "css-transform-generator", "css-animation-generator"],
    "css-filter-generator": ["css-color-converter", "css-glassmorphism-generator", "css-gradient-generator", "css-flexbox-generator", "css-grid-generator", "css-clamp-generator"],
    "css-color-converter": ["color-picker", "hex-to-rgb", "rgb-to-hex", "rgb-to-hsl", "hsl-to-rgb", "hex-to-hsl"],
    # Text tool clusters
    "word-counter": ["character-counter", "sentence-counter", "paragraph-counter", "reading-time-calculator", "text-cleaner", "text-line-break-remover"],
    "character-counter": ["word-counter", "sentence-counter", "text-cleaner", "text-to-slug-converter", "case-converter", "text-line-break-remover"],
    "case-converter": ["uppercase-converter", "lowercase-converter", "title-case-converter", "text-to-slug-converter", "slug-generator", "word-counter"],
    "markdown-previewer": ["markdown-to-html-converter", "markdown-table-generator", "html-to-markdown-converter", "lorem-ipsum-generator", "text-cleaner", "slug-generator"],
    "markdown-to-html-converter": ["html-to-markdown-converter", "markdown-previewer", "markdown-table-generator", "html-beautifier", "html-entity-encoder", "text-cleaner"],
    "html-to-markdown-converter": ["markdown-to-html-converter", "markdown-previewer", "markdown-table-generator", "html-minifier", "html-entity-decoder", "text-cleaner"],
    "text-diff-checker": ["find-and-replace-tool", "text-cleaner", "regex-tester", "remove-duplicate-lines", "sort-lines-alphabetically", "character-counter"],
    "find-and-replace-tool": ["text-diff-checker", "regex-tester", "text-cleaner", "remove-duplicate-lines", "sort-lines-alphabetically", "case-converter"],
    "text-to-slug-converter": ["slug-generator", "url-encoder", "url-decoder", "text-cleaner", "text-line-break-remover", "case-converter"],
    # Math cluster
    "percentage-calculator": ["percentage-increase-calculator", "percentage-decrease-calculator", "discount-calculator", "profit-margin-calculator", "ratio-calculator", "proportion-calculator"],
    "percentage-increase-calculator": ["percentage-decrease-calculator", "percentage-calculator", "growth-rate-calculator", "roi-calculator", "profit-margin-calculator", "investment-return-calculator"],
    "percentage-decrease-calculator": ["percentage-increase-calculator", "percentage-calculator", "discount-calculator", "markup-calculator", "profit-margin-calculator", "break-even-calculator"],
    "average-calculator": ["median-calculator", "mode-calculator", "standard-deviation-calculator", "mean-calculator", "ratio-calculator", "proportion-calculator"],
    "fraction-calculator": ["decimal-to-fraction", "fraction-to-decimal", "mixed-number-calculator", "gcd-calculator", "lcm-calculator", "scientific-calculator"],
    "binary-to-decimal": ["decimal-to-binary", "hex-to-decimal", "decimal-to-hex", "octal-converter", "binary-calculator", "scientific-notation-converter"],
    "decimal-to-binary": ["binary-to-decimal", "decimal-to-hex", "hex-to-decimal", "octal-converter", "binary-calculator", "scientific-notation-converter"],
    # Student cluster
    "gpa-calculator": ["cgpa-calculator", "percentage-to-gpa-calculator", "grade-calculator", "weighted-grade-calculator", "final-grade-calculator", "exam-percentage-calculator"],
    "grade-calculator": ["gpa-calculator", "cgpa-calculator", "weighted-grade-calculator", "final-grade-calculator", "exam-percentage-calculator", "marks-percentage-calculator"],
    "pomodoro-timer": ["study-time-calculator", "study-schedule-generator", "revision-schedule-generator", "exam-countdown", "assignment-countdown", "flashcard-generator"],
    "exam-countdown": ["assignment-countdown", "semester-countdown", "pomodoro-timer", "study-time-calculator", "study-schedule-generator", "revision-schedule-generator"],
    # Date cluster
    "age-calculator": ["date-difference-calculator", "days-between-dates", "leap-year-checker", "day-of-week-calculator", "week-number-calculator", "date-format-converter"],
    "date-difference-calculator": ["days-between-dates", "weeks-between-dates", "months-between-dates", "business-days-calculator", "time-difference-calculator", "age-calculator"],
    "unix-timestamp-generator": ["unix-timestamp-converter", "date-format-converter", "date-addition-calculator", "day-of-week-calculator", "week-number-calculator", "time-difference-calculator"],
    # Finance cluster
    "loan-emi-calculator": ["mortgage-calculator", "loan-payment-calculator", "loan-interest-calculator", "simple-interest-calculator", "compound-interest-calculator", "salary-calculator"],
    "simple-interest-calculator": ["compound-interest-calculator", "loan-interest-calculator", "loan-emi-calculator", "investment-return-calculator", "cagr-calculator", "sip-calculator"],
    "compound-interest-calculator": ["simple-interest-calculator", "sip-calculator", "investment-return-calculator", "cagr-calculator", "retirement-calculator", "savings-goal-calculator"],
    "cagr-calculator": ["investment-return-calculator", "sip-calculator", "roi-calculator", "compound-interest-calculator", "retirement-calculator", "growth-rate-calculator"],
    "discount-calculator": ["sale-price-calculator", "percentage-calculator", "markup-calculator", "profit-margin-calculator", "tip-calculator", "split-bill-calculator"],
    "salary-calculator": ["hourly-to-yearly-salary", "yearly-to-hourly-salary", "tax-percentage-calculator", "loan-emi-calculator", "budget-calculator", "net-worth-calculator"],
    # Business cluster
    "roi-calculator": ["roas-calculator", "profit-calculator", "revenue-calculator", "profit-margin-calculator", "break-even-calculator", "growth-rate-calculator"],
    "conversion-rate-calculator": ["ctr-calculator", "cpm-calculator", "cpc-calculator", "roas-calculator", "customer-acquisition-cost-calculator", "customer-lifetime-value-calculator"],
    "profit-calculator": ["revenue-calculator", "roi-calculator", "profit-margin-calculator", "gross-margin-calculator", "net-margin-calculator", "break-even-calculator"],
    # Image cluster
    "image-resizer": ["image-cropper", "image-compressor", "social-media-image-resizer", "youtube-thumbnail-resizer", "instagram-image-resizer", "image-dimension-checker"],
    "image-compressor": ["image-resizer", "jpg-to-webp", "png-to-webp", "webp-to-jpg", "jpg-to-png", "png-to-jpg"],
    "image-to-base64": ["base64-to-image", "base64-encoder", "base64-decoder", "image-metadata-viewer", "favicon-generator", "app-icon-generator"],
    "image-metadata-viewer": ["image-dimension-checker", "image-aspect-ratio-calculator", "image-pixel-color-picker", "image-resizer", "image-compressor", "image-to-base64"],
    # Color cluster
    "color-picker": ["color-palette-generator", "hex-to-rgb", "rgb-to-hex", "random-color-generator", "contrast-checker", "css-color-generator"],
    "hex-to-rgb": ["rgb-to-hex", "rgb-to-hsl", "hsl-to-rgb", "hex-to-hsl", "css-color-converter", "color-picker"],
    "contrast-checker": ["wcag-contrast-checker", "color-blindness-simulator", "color-picker", "hex-to-rgb", "rgb-to-hsl", "css-color-converter"],
    "color-palette-generator": ["complementary-color-generator", "analogous-color-generator", "triadic-color-generator", "gradient-generator", "random-color-generator", "color-picker"],
}

# Apply fixes
updated_desc = 0
updated_related = 0
for tool in data["tools"]:
    slug = tool["slug"]
    # Fix description
    if slug in descs:
        if tool["description"] != descs[slug]:
            tool["description"] = descs[slug]
            updated_desc += 1
    # Fix related links
    if slug in related_fixes:
        new_related = related_fixes[slug]
        if tool.get("related", []) != new_related:
            tool["related"] = new_related
            updated_related += 1

# Fix site description
data["site"]["description"] = "230 free browser-based tools for developers, students, and professionals. Your data stays in your browser — no uploads, no sign-up."

with open("tools.json", "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Updated {updated_desc} descriptions")
print(f"Updated {updated_related} related link sets")
print(f"Total tools: {len(data['tools'])}")
